import React from 'react'
import { Col, Container, Row } from 'react-bootstrap'

const Policies = () => {
    return (
        <>
         <Container style={{marginTop:'20px'}}>
            <Row>
                <h2 className="text-primary">Terms And Conditions</h2>
                <Col md={12}>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias illo non? Accusantium tempore earum culpa totam necessitatibus ex neque?</p> 
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos ad suscipit fuga perferendis fugit nisi aperiam voluptate reiciendis, repellendus ipsam amet nulla quaerat dignissimos laboriosam at deleniti veniam possimus voluptatum exercitationem, impedit fugiat hic magni eius animi. Quae ex alias fugit impedit velit molestias recusandae non? Doloremque ullam amet ipsa consequuntur, in sit debitis quis voluptate, facilis, dicta quasi? Nisi ratione numquam non odit vero assumenda fugiat, iste rerum similique deleniti ullam quibusdam ipsum repellendus, architecto aliquid, ea facere tenetur vitae quam obcaecati natus accusamus quod! Fugit perferendis modi accusamus expedita, officiis impedit nobis, doloribus asperiores, unde consequatur consectetur officia.</p>

                </Col>
                </Row>     
        </Container>   
        </>
    )
}

export default Policies
